version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
    depends_on:
      - mongodb
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
